### ISSUE TITLE
SearchAny In Coq-8.4pl4/pl5

### ISSUE THREAD

**Issue by mmalvarez** [cpitclaudel/company-coq#1]
This plugin looks awesome! I noticed that the only available version of the SearchAny enhancement for Coq that you provide seems to be built on Coq 8.4pl2 (https://github.com/cpitclaudel/coq/tree/V8.4pl2-SearchAny).

Because I used 8.4pl4 for my work, I created a patch of the differences between 8.4pl2-SearchAny and 8.4pl2. For convenience, I've created a gist containing the patch: https://gist.github.com/mmalvarez/6496f2ecbfe2fd661d52

I've been able to successfully apply this patch to Coq 8.4pl4 and 8.4pl5, which allows for the use of the symbol-search features of company-coq in these versions of Coq. It might be worthwhile to put the patch into the company-coq repository, or a link to the patch it into its readme, for the benefit of others who use these versions.

Thanks!

**Comment by cpitclaudel** [comment]
That's pretty cool, thanks! The `SearchAny` part is not strictly necessary though: it's possible to make the patch less intrusive by just taking the parts regarding `Set/Unset Search Minimal`. That option makes all search routines return the results in minimized, names-only form. I'm hoping that it will be possible to include it in Coq trunk, and from there to back-port it into the older versions.

I'll leave the issue open until then! And I'll post a link to a cleaned up patch soon. 

Small side note: I've been working on a bunch of changes in the "experimental" branch; if you want to check it out it has plenty of new cool features like auto-completing package names (after `Require Import`, and a limited form of symbol completion (It just scans the current buffer for Lemma definitions). It also auto-completes the names of hypotheses in the context. I'll merge it soon-ish, but some testing would be very welcome!

If you use the branch you'll want to set `company-coq-autocomplete-symbols-dynamic` instead of `company-coq-autocomplete-symbols` (`company-coq-autocomplete-symbols` now designates this simpler feature that doesn't require a patched version of Coq, and it's on by defaut)

Glad you like the plugin!

**Comment by cpitclaudel** [comment]
Another note: It might actually be the case that the third patch in the patchset that you posted can actually be applied directly, and implements all of the `Set Search Minimal` feature.

**Comment by mmalvarez** [comment]
Thanks! Having a cleaner patch would be great; I generated the one I linked above pretty naively, so it would be great to make it less invaisive.

When I get the chance I'll take a look at the experimental branch; those extra features you mentioned look like they could be useful.

**Comment by cpitclaudel** [comment]
Here's a cleaner patch: https://github.com/cpitclaudel/company-coq/blob/master/SearchMinimal.patch

**Comment by cpitclaudel** [comment]
The patches have landed in 8.5, so it's just a matter of enabling one setting there. On 8.4 the patch seems reasonably stable too; I'll a note to the README, but I think this can be closed :)
