### ISSUE TITLE
Update Proof General installation procedure ?

### ISSUE THREAD

**Issue by atrieu** [cpitclaudel/company-coq#212]
Hi, the current installation instructions recommend to git clone the proof general repo. However, they seem to recommend to install it through MELPA, same as company-coq.

Any explanation on why the discrepancy ? Or is it just that the instructions haven't been updated in a while ? ;-)

**Comment by cpitclaudel** [comment]
It's just that the instructions are old and the MELPA recipe still somewhat experimental

**Comment by erikmd** [comment]
@atrieu indeed ProofGeneral `master` is now published in MELPA, and it is also `use-package`-compliant since last month, so we'll be able to update at the same time:

1. https://proofgeneral.github.io/ (which deals with MELPA but not `use-package`)
2. https://github.com/cpitclaudel/company-coq#readme (which only deals with git clone)

FYI I documented an automatic installation of tuareg+merlin+PG+company-coq in https://github.com/erikmd/tapfa-init.el (in French) so I plan to update https://proofgeneral.github.io/ accordingly very soon (this week-end…)

**Comment by cpitclaudel** [comment]
I think updating the instructions would be good :) Wanna prepare a patch?

**Comment by erikmd** [comment]
Hi @cpitclaudel, indeed (sorry for the lack of reactivity…) I can prepare this now.
