### ISSUE TITLE
jump to definition in current file fails if no _CoqProject or no -Q

### ISSUE THREAD

**Issue by aa755** [cpitclaudel/company-coq#238]
````
[abhishek@optiplex temp]$ ls
test.v
[abhishek@optiplex temp]$ cat test.v 
Require Import NArith.
Definition x := 1.
Definition y:=x.
````
When I open `test.v`, take the cursor to the "x" in the last line, and press `M-.`, I get "no location found for 'x'". The problem disappears when I add the following `_CoqProject` file:
````
[abhishek@optiplex temp]$ cat _CoqProject 
-Q . test
````

However, just having a `_CoqProject` is not sufficient. It seems the _CoqProject should have a -Q directive covering the current file. When I changed the _CoqProject as follows, jump-to-definition stopped working again:
````
[abhishek@optiplex temp]$ mkdir tt
[abhishek@optiplex temp]$ cat _CoqProject
-Q tt test
[abhishek@optiplex temp]$ ls
_CoqProject  test.v  tt
````

**Comment by aa755** [comment]
This may be the intended behavior. If so, it may help to change the error message to "no location found. ensure that there is a -Q for current file"

**Comment by cpitclaudel** [comment]
Definitely not intended, and certainly not pleasant.  Thanks for the report!

The problem comes from the qay Coq reponds to Locate queries:

```
<prompt>Coq < 32 || 0 < </prompt>Timeout 1 Locate x.
Constant test.x

<prompt>Coq < 34 || 0 < </prompt>Timeout 1 Locate Library test.
Toplevel input, characters 25-29:
> Timeout 1 Locate Library test.
>                          ^^^^
Error: Unable to locate library test.
```

PG recently starting passing `-topfile` to Coq, so instead of reporting `Top.x`, Coq now says `test.x`.
I *think* this is a Coq bug, to some extent, but I'm not super familiar with the semantics of `-topfile`.  @erikmd, do you think `topfile` should influence the output of Locate?

In any case, can you try the following?

```elisp
(require 'company-coq)

(defun ~/company-coq-library-path (lib-path mod-name fallback-spec)
  (and (equal lib-path "")
       buffer-file-name
       (equal (concat mod-name ".v")
              (file-name-nondirectory buffer-file-name))
       (current-buffer)))

(advice-add #'company-coq-library-path :before-until #'~/company-coq-library-path)
```

**Comment by erikmd** [comment]
@cpitclaudel Yes, I think so, `topfile` should influence the output of Locate, and it seems to me there is no Coq bug: basically, with a recent Coq and PG, when you are editing a file (with no _CoqProject or so), the ambient file basename is understood as the namespace of the constants you define inside.

So that explains the output of the qualid of `x` (`Locate x.` → `Constant test.x`)

However, the `Locate Library test` fails because the `test` module itself has not yet been defined and stored in a .vo or so, because its definition is on-going.

And note in passing that @aa755 's attempt to create a `_CoqProject` with
```
-Q . test
```
is not a proper solution, because it would ultimately lead to defining `test.test.x` !

I just skimmed the snippet Clément proposed but I guess this is the way to go: adapting company-coq's algorithm so that if the module returned by `Locate` coincides with the file basename, the lookup is performed within the current buffer.

**Comment by aa755** [comment]
`test.test.x` was precisely my intention for the fully qualified name of `x` so, it is the proper solution for what I need. Everything works fine as long as there is a -Q covering the current file. That part should keep working at least.

**Comment by aa755** [comment]
I would say there is a bug in Coq. When  I have a `-Q . test` in my _CoqProject, I expect `x` in `test.v` to have the fully qualified name as `test.test.x`, exactly as Locate `x` says. So it is inconsistent for `Locate Library test` to fail.

**Comment by erikmd** [comment]
@aa755 OK I see what you mean. So maybe you could file a Coq bug report? while mentioning the full `coqtop` command line run by PG in the two cases (i.e., you can get them by doing <kbd>M-x list-processes RET</kbd> in emacs)

**Comment by aa755** [comment]
@cpitclaudel : After adding that snipped to emacs, jump to definition works even if there is no _CoqProject.

**Comment by aa755** [comment]
About the coq bug, sorry, thinking more about it, I am now not completely sure whether there is a bug in Coq. In one sense, the inconsistency between the behavior of `Locate x` and `Locate Library test` w.r.t. whether the module test exists is somewhat unfortunate. But Coq does explicitly say in the error message that it couldn't find any such .vos file (`Error: Unable to locate library test. (While searching for a .vos file)`), which really doesn't exist. Also, if the fix is not necessary for company-coq to work, it make it harder to argue for a change in Coq.

**Comment by cpitclaudel** [comment]
Ok, please ping me in a week if I haven't had time to return to this to write a clean patch ^^ I'm busy with PLDI-related stuff this week. Thanks again for the report!
