### ISSUE TITLE
Using prettify-symbols-alist only impacts source buffer, not goals or response buffers

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#34]
I tried adding this to my .emacs:

```
(add-hook 'coq-mode-hook
          (lambda ()
            (set (make-local-variable 'prettify-symbols-alist)
                 '((":=" . ?≝)
		   ("Proof." . ?∵)
		   ("Qed." . ?■)
                   ("Defined." . ?□)
		   ("Time" . ?⏱)
		   ("Admitted." . ?😱)
		   ("#+" . ?⨥)
		   ("#-" . ?⨪)
		   ))
	    (company-coq-initialize)
	    ))
```

and adds the new prettified symbols in the source window, but does nothing in the goals or response windows.  Do I need some other setting?

**Comment by cpitclaudel** [comment]
Indeed, this one had been bugging at some point (but then it got buried in my TODO list). It's ticky to get right because the prettification-alist can be made file-local, so it's not obvious where to take the prettification alist from for the goal and response buffers.

It turns out that the new architecture makes this much easier, so this should be fixed on the `massive-cleanup` branch! Thanks for reporting it :)
