### ISSUE TITLE
C-c, C-RET should hide the dropdown box

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#5]
I know it means that I'm not making good use of the completion (so maybe you will mark this as an intentional WontFix), but it might be nice if, when I type `reflexivity` and press `C-c C-RET`, I'm not left with an inconsistently blue buffer (which becomes consistent when I close the dropdown), and instead the dropdown autocloses.

**Comment by cpitclaudel** [comment]
Is this inconsistency due to the completions overlay? (I think) I can repro this when I start completing at the bottom of the window, forcing the completions to pup up above the current line instead of under. Also, this only happens if you're typing `reflexivity` before an already-inserted period, right?

This is probably part of a host of problems related to the way popups are drawn that will surface with time. The long-term goal for company is to move to GUI popups.

In the mean time it should easy to make the shortcut for (proof-goto-point) also call (company-abort). I'll do that soon.

**Comment by JasonGross** [comment]
The inconsistency in display is not the main issue; the main issue is that down arrow does the wrong thing after proof-goto-point (I want it to move down a line; it instead changes the dropdown selection).  Sorry for the slightly misleading description.

This occurs primarily when adding new cases in the middle of a `repeat match goal with ... end.`, but also when I'm editing `Definitions`.

Anyway, I think your fix is the right one, though you may also want to do this on the other proof-moving commands (I never use the other ones, though).  Thanks!
