### ISSUE TITLE
Blocks in braces not foldable

### ISSUE THREAD

**Issue by Zimmi48** [cpitclaudel/company-coq#67]
Hi,
I have the impression that the braces are not detected as blocks which can be folded. At least, not for me with the following example:
```
assert (H4_1 : f' x > 0). {
  apply H3.
  split; left; assumption.
}
```
Do you think that could be linked with the fix of #57 ?
Thanks!

**Comment by cpitclaudel** [comment]
Hi Théo,

No, it's not a consequence of #57; more of an independent issue. The issue is that braces have sufficiently many meanings in Coq that reliably detecting which braces are proof section delimiters vs. implicit arguments or classes or user notations is hard.

I can look into supporting braces at the end of a line. I'll let other voice concerns if anyone thinks it could be an issue.

**Comment by jonleivent** [comment]
I would have thought this was a consequence of #57 as well, specifically the part where you made braces that don't start a line be not considered proof braces.  If it is, maybe the fix there should be restricted to just not allowing folding for one-line braces, since they can't fold anyway?

**Comment by cpitclaudel** [comment]
@jonleivent That didn't happen in #57, did it? What I did there was require a space or a newline after braces, so that check works here. The test that's preventing these braces to fold is the one that disallows bullets "in the middle of a line". It's not obvious that it should apply to braces as well, but it does atm.

**Comment by Zimmi48** [comment]
Thanks!

**Comment by cpitclaudel** [comment]
Sure, thanks for the feedback!
