### ISSUE TITLE
Subscript confusion

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#69]
Company-coq is rendering both H0 and H__0 as H with subscript 0 in the source window, and no longer rendering either in the goals window.

(Something is wrong with uploading, else a nice screenshot would be here.)

**Comment by jonleivent** [comment]
Uploading is working again, so here's the promised nice screenshot:

![screenshot-emacs24 jess home-6](https://cloud.githubusercontent.com/assets/7363878/12686312/fac071b6-c696-11e5-804a-73aea5f66078.png)

**Comment by cpitclaudel** [comment]
Thanks for pointing this out. The goals buffer problem is a bug; I just fixed it (https://github.com/cpitclaudel/company-coq/commit/ab976e468bb3371d08cc8703c1de28720fe8c88e).

The other part is mostly a feature, but I'm open to debating it. Here's the issue:

* PG has a subscript facility; no one uses it. But people are excited when they learn that it exists; except for the fact that it requires a double underscore (`x__1`)
* Looking at the whole stdlb, almost all identifiers followed by one or more digits would be best rendered as subscripts. The only counter-example I found was `Utf8`. Prettifying `x0` into `x₀` would be a gain for most users, I think. Especially since I'm not changing the font size, so it doesn't break horizontal alignment
* Similarly, plenty of examples in the test suite are written `x_1` and should be subscripts, but I don't want to introduce ambiguities. Of course `abc_def` is usually not a subscript, so it shouldn't be rendered as such.
* When one want subscripts made of letters, `x__abc` seems rather acceptable. But then there's no point in showing the underscores: you can't get `abc` as a subscript without them.

Based on these constraints, I decided to render numbers at the end of an identifier as subscripts. When they are preceded by a `_`, that too gets subscript treatment, but it's not hidden. Then there was the `x__abc` case, where hiding the underscore was not going to cause conflicts either. The last decision was what to do with `x__1`. PG hides the underscores, so I decided to do the same. At least it's consistent with the `x__abc` case. And it's uncommon: there isn't a single occurence of this in the whole stdlib, so I guess anyone who was using that was using it because of PGs support.

What do you think?

**Comment by jonleivent** [comment]
I don't think that two distinct spellings should ever result in the same rendering, as that could be very confusing (although in Coq terms, probably not unlike hiding implicits, etc.).  One could argue it is the user's fault, but it wouldn't be a very good argument unless this feature of Company-Coq was well-known and preceded all script usages of such spellings - which is not the case.

So, let's list your rules:

1. numbers at end, possibly preceded by a single underscore - all are subscripted, none are hidden (including the underscore)

2. If not 1, then double underscores that don't start an identifer are hidden, and everything that follows is a subscript

This makes x1 and x__1 render the same way.  I didn't know that PG renders x__1 as x sub 1 with no underscores showing - is that an option that needs to be turned on?  Do others use this option?

If you want to be compatible with PG, then I suggest a company-coq option to switch between a PG-compatible mode and an company-coq auto-subscriting mode.  If the user selects not-PG compatible, then I suggest subscripting x__1 as x sub __1 (hiding nothing).  If PG compatible, then there is no scripting without __.

**Comment by cpitclaudel** [comment]
The unicode math option of PG does this (rendering `x__1` as `x sub 1`). Did you ever come across `__[number]` in a Coq script though? It seems really infrequent.

I'm afraid of having too many options, first because users don't explore them (PG has plenty of cool features that no one knows about), and second because it's hard to test how they interact (as exemplified by the number of bugs that you already reported; thanks!).

**Comment by cpitclaudel** [comment]
How do you feel about rendering `x__a` as `x sub a`? That one isn't ambiguous. We could disable `x__1` and keep only `x__a`, but the lack of symmetry is a bit frustrating.

**Comment by cpitclaudel** [comment]
I think my own logic is faulty ere. Either everybody is already using `x__1` for their subscripts, and adding prettifying `x1` will confuse everyone, so it shouldn't be done. Or nobody is using `x__1`, and in that case what's the point of supporting it?

**Comment by cpitclaudel** [comment]
All right, here's a new proposal:

```
* a123 -> a sub 123
* a_123 -> a sub _123
* a__123 -> a sub __123
* abcd -> abcd
* a_bcd -> a_bcd
* a__bcd -> a sub bcd
```

The only case where anything is hidden would be `a__[letters]`. Thus there's only one way to get any subscript.

Opinions?

**Comment by cpitclaudel** [comment]
Another option of course is this:

```
* a123 -> a123
* a_123 -> a_123
* a__123 -> a sub 123
* abcd -> abcd
* a_bcd -> a_bcd
* a__bcd -> a sub bcd
```

Which is essentially PG style. I don't like it: nobody will benefit from it unless they are told it's there.

**Comment by jonleivent** [comment]
Is there a problem with having a switch that chooses between PG's method and your new-fangled auto-subscripting?  The problem I see is that if you force something that isn't compatible with PG's method, you're bound to force some lover of that method to surface to charge you with destroying his/her happiness.  So, I suggest a three-way switch: no subscripting, PG-compatible, automatic.  If possible.

Also, wondering if you could use the fact that a prime is an identifier character.  Maybe as a way of cancelling a subscript that isn't wanted?  Like a'1  would render as a1 not a sub 1.  Maybe as a way of doing superscripts?  What about double-primes (not double quotes) being like double-underscores, except as superscripters?  I don't know how many people like superscripts, while I agree that it's a safe bet that many mathers will like auto-subscripts.  So, maybe it would just work as a way to cancel auto-subscripting so that someone can have a1 as well as a sub 1.  Or, maybe anyone who wants that is asking for too much...

**Comment by jonleivent** [comment]
Oh - I see you said you are afraid of too many options.  But, in this case, I would make automatic subscripting the default.  Then, wait until someone complains, and tell them about the other options (or put it in the readme somewhere).  In other words - use the default to encourage usage.  It's company-coq doing the behavioral-economic nudge, which is all the rage.

**Comment by cpitclaudel** [comment]
> Is there a problem with having a switch that chooses between PG's method and your new-fangled auto-subscripting? The problem I see is that if you force something that isn't compatible with PG's method, you're bound to force some lover of that method to surface to charge you with destroying his/her happiness. So, I suggest a three-way switch: no subscripting, PG-compatible, automatic. If possible.

I don't think that's needed: it's easy to disable the company-coq layer (which is on by default), and it's easy to enable the PG layer (which is off by default).

I think we have a cool occasion to redesign this feature. I'd  like to get it right; I don't think the PG way was ideal. You've convinced me that my ideal attempt wasn't there either (I agree that two different variables being rendered the same is undesirable). I'll fix that.

**Comment by cpitclaudel** [comment]
> Oh - I see you said you are afraid of too many options. 
Exactly

> But, in this case, I would make automatic subscripting the default. Then, wait until someone complains, and tell them about the other options (or put it in the readme somewhere). In other words - use the default to encourage usage. It's company-coq doing the behavioral-economic nudge, which is all the rage.
I think it works well, too :)

**Comment by jonleivent** [comment]
OK - cool!  Some other odds-and-ends that occurred to me:  Consider really unlikely sequences like _'  - maybe that can be a cancel subscript (like an escape), or a superscript?  Is it possible to have multiple levels, like a__b__1?  Or, am I going overboard into the latex arena?

**Comment by cpitclaudel** [comment]
I think `_'` will already act as an escape: I only allow a-z0-9 in subscripts. I think I like `''` as a superscript marker better; but I wonder if it should be hidden (like `__` in `a__abc`?)

**Comment by jonleivent** [comment]
I think that primes, unlike underscores, are almost always going to occur at the end of identifiers in those cases where users want them to be visible.  (Unless someone likes Klingon identifiers - probably not as far-fetched as it sounds.)  So, use the opportunity to render non-leading, non-trailing primes as hidden markers for superscripts?  Or, maybe someone is going to want the exponent operator ^ to be rendered as a hidden marker for a superscript?  Maybe there is just not enough agreement on the proper usage for subscripts...

**Comment by cpitclaudel** [comment]
Indeed, coming up with a non-controversial option is going to be tricky for superscripts.
I vote for leaving it at that for now: `abc123` gets prettified, there are no ambiguities any more, and unless you really want it (by using `__`) nothing gets hidden.

**Comment by cpitclaudel** [comment]
I just pushed a small change that allows primes after subscripts.

**Comment by JasonGross** [comment]
I think that `abc__abc` should not display as `abcabc`; subscripting the letters is fine, but if you're not going to subscript the letters, don't hide the underscores.  (The letters are not subscripted on my (remote, terminal) machine.)

**Comment by cpitclaudel** [comment]
Thanks for pointing this out Jason. Should be fixed now :)

**Comment by cpitclaudel** [comment]
I think this has matured enough now, especially with the recent changes in 6d4d7df74b336fad8dd5e2197c3294059c78af1c. For reference, the current implementation does the following:

```
abc123 → abc₁₂₃
abc_123 → abc_₁₂₃
abc__123 → abc__₁₂₃
abcjkl → abcjkl
abc_jkl → abc_jkl
abc__jkl → abcⱼₖₗ
```

Additionally, the new implementation reveals the `__` separator when the point is next to it, to allow for easier editing.
