### ISSUE TITLE
M-. is confused about automatically generated induction schemes

### ISSUE THREAD

**Issue by wilcoxjay** [cpitclaudel/company-coq#83]
Consider the following code.

```
Inductive foo := .

Definition foo_recf : foo -> False.
  apply foo_rec.
Defined.
```

If you load this and bring the proof state down to after `Defined.` and then move point over `foo_rec` in the proof and press `M-.` you will be brought instead to `foo_recf`. 

It's not entirely clear what should happen in this situation, since there is no point in the file that literally defines `foo_rec`. But it seems pretty clear that the current behavior is not good :) How is it that company-coq can direct me to something with a different (albeit similar) name?

**Comment by cpitclaudel** [comment]
> It's not entirely clear what should happen in this situation, since there is no point in the file that literally defines foo_rec.

Indeed; I guess we could special-case foo_rec, foo_rect, and foo_ind.

> But it seems pretty clear that the current behavior is not good :) How is it that company-coq can direct me to something with a different (albeit similar) name?

That's an unfortunate side-effect of the way company-coq looks up a name. It (essentially) calls `Locate foo_rec`, parses the output of that, then finds the corresponding file using `Locate Library`, and finally opens that file and searches it to find `Definition foo_rec` or `Record foo_rec` or `Inductive foo_rec` or `Fixpoint foo_rec` or any of a bunch of other options. Since it doesn't find any of these, it falls back to looking for `foo_rec`, and it finds `foo_rect`. I'll update the fallback regexp to only find exact matches.

Btw, the reason to have a falback in the first place it to find fields of records: with `Record A := {AA: nat; BB:nat }`, `Locate AA` returns `Constant Top.AA`, which gives me no way of guessing that it's a record field (if I knew that, I could issue another command to find out the name of the record type). Contrast this with the Inductive case, where the output would be `Constructor Top.AA`. Jason recently pointed out to me that Check {| AA := _ |}` would probably give useful information, so I'll implement this; it should reduce the need for a fallback.

**Comment by wilcoxjay** [comment]
That sounds great, thanks! 

I'm not a huge fan of special-casing _rec, _rect, and _ind, because there are certainly projects that turn off automatic generation of induction schemes. But perhaps it would be reasonable to issue a warning in the case where you are falling back and the name ends in one of those suffixes. I am not sure whether this is too weird from a UI perspective, since company-coq doesn't really issue other warnings to users.

**Comment by cpitclaudel** [comment]
Not sure what to think about special-cases either. I've implemented your suggestion of a warning message, and added support for record fields. Let me know what you think!
