### ISSUE TITLE
feature wish: highlighting tactic-in-term

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#84]
Would it be possible to have an emacs face variable for the new-in-8.5 "ltac:(...)" syntax?  I would like to set a background highlighting for this (including the ltac:( and ) delimiters).  It would be nice to be able to spot these embedded in Gallina more easily.  An difficulty might be that a regexp to match this would require that extended balanced-paren regexp Emacs extension that blows out the stack, while matching it using forward-sexp would be easy.

If that is too difficult, maybe just be able to highlight the face of "ltac:"?

**Comment by jonleivent** [comment]
I did this for now:

(defvar coq-user-solve-tactics-db
  '(
    ("ltac" nil "ltac:(#)" t "ltac")
    ))

**Comment by cpitclaudel** [comment]
This is a good idea. The highlighting engine also supports custom matcher functions, so matching balanced parentheses isn't hard. The hard part, on the other hand, is when matching backwards. Since the construct can span multiple lines, we'll have to add plenty of complications to highlight properly. That part is probably what makes it hard to implement.

I think adding a face to ltac: will work great; we should probably add the same face to constr:.  This should be done in PG, though; we can make a new face based on font-lock-preprocessor-face, probably; I don't think we use that one anywhere else. We could also add `bold` to it, since it doesn't look very different from the base font in the default theme.

**Comment by jonleivent** [comment]
Just a thought: why is it (somewhat) easy to add a keyword to an existing face, but not so easy to create a new face?  It would be nice to have some way to add faces in my .emacs file, for instance - then add keywords to that face.  I shouldn't be forced to use just those faces that are already defined, like font-lock-preprocessor-face, or the one I used: coq-user-solve-tactics-face.

But, I agree that a similar highlighting could apply to ltac:(..), constr:(..), uconstr:(..), etc.

**Comment by cpitclaudel** [comment]
Creating and using new face is really easy actually; here's an example:

```
(with-eval-after-load 'coq
  (defface coq-context-qualifier-face
    '((t :inherit font-lock-preprocessor-face :weight bold))
    "Face used for ltac:, constr:, uconstr:."
    :group 'proof-faces))

(defun my/add-coq-keywords ()
  (font-lock-add-keywords nil '(("\\_<\\(ltac\\)\\_>:" 1 'coq-context-qualifier-face))))

(add-hook 'coq-mode-hook #'my/add-coq-keywords)
```

`coq-user-solve-tactics-db` and the like are just a convenient way to enforce consistency, but the mechanism in the example above is the general one :)

**Comment by cpitclaudel** [comment]
So which keywords do we want to highlight in this way? ltac, constr, uconstr; are there others?

**Comment by jonleivent** [comment]
Thanks for that face definition tidbit!  Works nicely.  I added a yellow background to make it easier to see these context qualifiers.

I think the only keywords in this set so far are ltac, constr and uconstr.  There are the other Tactic Notation types besides constr and uconstr, but I don't think they can be used outside of Tactic Notation specs.

**Comment by cpitclaudel** [comment]
[PR #59](https://github.com/ProofGeneral/PG/pull/59) :)
